### ISSUE TITLE
Where can I find the definition of entity "pig"? 

### ISSUE THREAD

**Issue by Haishion** [Microsoft/malmo-challenge#28]
The movement rule and frequency of pig entity aren't clear enough.

**Comment by mfuntowicz** [comment]
Hi @Haishion, 

Thanks for your feedback.
Unfortunately, the pig is managed by Minecraft directly, and we don't have any behavioral clues regarding decisions made by the Minecraft's AI.

At this point you should just consider that the pig is moving randomly.
Hope it helps, 

Morgan
