### ISSUE TITLE
ImportError: Module use of python27.dll conflicts with this version of Python

### ISSUE THREAD

**Issue by Haishion** [Microsoft/malmo-challenge#29]
Hi, I used Python 3.5 to install all the things. However, when I try to run baseline file, there is such an error.

**Comment by mfuntowicz** [comment]
Hi @Haishion,

If you installed precompiled Malmo package (downloading the zip, or using the install scripts) you'll have such inconsistency as Malmo precompiled package is provided only for python2.7

If you want to use Malmo for python 3.5 you will need to compile everything on your side, following :
- [Build for Windows](https://github.com/Microsoft/malmo/blob/master/doc/build_windows.md)
- [Build for Linux](https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md)
- [Build for Mac](https://github.com/Microsoft/malmo/blob/master/doc/build_macosx.md)

The easiest workaround would be to use Python2.7.

I'm closing this issue, as it's more related to Malmo and not the challenge directly.

Feel free to reopen in any case.
Morgan
