### ISSUE TITLE
no module named malmopython

### ISSUE THREAD

**Issue by onlytailei** [Microsoft/malmo-challenge#7]
When execute pig_chase_baseline.py
```
OpenCV found, setting as default backend.
Traceback (most recent call last):
  File "pig_chase_baseline.py", line 38, in <module>
    from environment import PigChaseEnvironment, PigChaseSymbolicStateBuilder
  File "/home/tyler/Software/Malmo/malmo-challenge/ai_challenge/pig_chase/environment.py", line 27, in <module>
    from MalmoPython import MissionSpec
ImportError: No module named MalmoPython
```

But nothing happened for malmo examples.

**Comment by DaveyBiggers** [comment]
Ah, you may need to add MalmoPython to your PYTHONPATH -  or copy (eg) MalmoPython.so into the folder where you are running pig_chase_baseline.py.
Let me know if this works and I'll update the installation instructions accordingly.

**Comment by onlytailei** [comment]
```
copy (eg) MalmoPython.so into the folder where you are running pig_chase_baseline.py.
```
Thank you Davey. After copy the file, it works.
The other problem is that sometimes the python file cannort find the server, even though I have already started the servers with appropriate ports.

**Comment by katja-hofmann** [comment]
Hi @onlytailei,

thank you for reporting back - I'm glad the proposed solution worked for you. We will update the documentation to reflect this.

For the server problems - could you create a new issue? Please include details on the platform / setup, and any error / output you receive to help us replicate and resolve this.
