### ISSUE TITLE
How is the game evaluated?

### ISSUE THREAD

**Issue by jingweiz** [Microsoft/malmo-challenge#9]
Hey,
So is the performance of the agent evaluated on the total score of the Agent0 & Agent1 or only the score of Agent1 (which I assumed is the one to be controlled by our algorithm)?
Cos during some test plays I observed that everytime Agent1 makes the final the move to corner the pig, both Agent0 and Agent1 get the 25 big reward; while if it's Agent0 who makes the final move to corner the pig, only Agent0 will get the 25 while Agent1 will not.
Thanks!

**Comment by katja-hofmann** [comment]
Hi @jingweiz - thank you for reporting this! This problem should be fixed in 2db6c6ef5e6473dcb6ecb7e7102f5d3fe4dc4a79. Could you pull these changes and let us know in case you experience any further problems?

Performance is evaluated on the score of agent 1 only.
